<?php

return [
    'title' => 'Frequently Asked Questions',
    'subtitle' => 'Search our FAQ for answers to anything you might ask.',

    'sections' => [
        'detection' => [
            'title' => 'AI Detection',
            'questions' => [
                'what_is_ai_detection' => [
                    'question' => 'What is AI content detection?',
                    'answer' => 'AI content detection is the process of identifying whether text was generated by artificial intelligence tools like ChatGPT, GPT-4, Claude, or other language models. Our advanced algorithms analyze writing patterns, linguistic markers, and stylistic characteristics to determine if content is AI-generated or human-written.'
                ],
                'how_accurate' => [
                    'question' => 'How accurate is your AI detection?',
                    'answer' => 'Our AI detection system maintains over 98% accuracy rate across various content types. We use advanced machine learning models trained on millions of samples to identify AI-generated content. However, accuracy may vary depending on the content length, quality, and the AI model used to generate it.'
                ],
                'supported_languages' => [
                    'question' => 'What languages does the AI detector support?',
                    'answer' => 'Our AI detector currently supports English, Spanish, French, German, Chinese, Japanese, and many other major languages. We\'re continuously expanding language support to serve a global audience.'
                ],
                'detection_time' => [
                    'question' => 'How long does it take to detect AI content?',
                    'answer' => 'Detection is nearly instantaneous. Most scans complete within 1-3 seconds, even for longer documents. Our advanced infrastructure ensures fast processing without compromising accuracy.'
                ],
                'can_detect_all_ai' => [
                    'question' => 'Can you detect content from all AI models?',
                    'answer' => 'Yes, our system can detect content generated by ChatGPT (GPT-3.5, GPT-4), Claude, Bard, Jasper, Copy.ai, and most other popular AI writing tools. We continuously update our detection algorithms to identify new AI models as they emerge.'
                ],
                'false_positives' => [
                    'question' => 'What about false positives?',
                    'answer' => 'While we strive for maximum accuracy, false positives can occasionally occur, especially with highly structured or formulaic human writing. We provide detailed confidence scores and highlighted sections to help you make informed decisions.'
                ]
            ]
        ],

        'humanization' => [
            'title' => 'AI Humanization & Rewriting',
            'questions' => [
                'what_is_humanization' => [
                    'question' => 'What is AI content humanization?',
                    'answer' => 'AI content humanization is the process of transforming AI-generated text to make it sound more natural, authentic, and human-like. Our tool rewrites content while preserving meaning, adding natural variations, personal touches, and stylistic elements that characterize human writing.'
                ],
                'how_does_rewriting_work' => [
                    'question' => 'How does the AI rewriting process work?',
                    'answer' => 'Our rewriting engine analyzes your content and restructures sentences, varies vocabulary, adjusts tone, and adds natural imperfections that make text appear human-written. It maintains the core message while making the content undetectable by AI detection tools.'
                ],
                'preserve_meaning' => [
                    'question' => 'Will rewriting change the meaning of my content?',
                    'answer' => 'No. Our advanced algorithms are designed to preserve the original meaning, key facts, and intent of your content. We only modify the writing style, sentence structure, and word choice to make it sound more natural and human-like.'
                ],
                'quality_after_rewrite' => [
                    'question' => 'Will the quality remain high after rewriting?',
                    'answer' => 'Absolutely. Our humanization process actually improves content quality by making it more engaging, natural, and readable. The rewritten content maintains grammatical correctness while adding human touches that enhance overall quality.'
                ],
                'rewriting_time' => [
                    'question' => 'How long does the rewriting process take?',
                    'answer' => 'Rewriting typically takes 5-15 seconds depending on content length. Shorter texts (under 500 words) process in about 5 seconds, while longer documents may take up to 30 seconds.'
                ],
                'plagiarism_check' => [
                    'question' => 'Is the rewritten content plagiarism-free?',
                    'answer' => 'Yes. Our rewriting process creates unique content that is completely original. The rewritten text will pass plagiarism checks while maintaining the core ideas and information from the original.'
                ]
            ]
        ],

        'usage' => [
            'title' => 'Usage & Features',
            'questions' => [
                'word_limits' => [
                    'question' => 'What are the word limits for each plan?',
                    'answer' => 'Essential plan: 150,000 words/month, Professional plan: 500,000 words/month, Premium plan: 300,000 words/month. Unused words don\'t roll over to the next month.'
                ],
                'file_upload' => [
                    'question' => 'Can I upload files for scanning?',
                    'answer' => 'Yes! Professional and Premium plans support batch file upload. You can upload PDF, DOCX, TXT, and other common document formats. The Essential plan supports text paste only.'
                ],
                'batch_processing' => [
                    'question' => 'Can I scan multiple documents at once?',
                    'answer' => 'Professional plan allows scanning up to 250 files simultaneously. Premium plan supports up to 50 files at once. Essential plan processes one document at a time.'
                ],
                'api_access' => [
                    'question' => 'Do you offer API access?',
                    'answer' => 'Yes, API access is available for Professional and Premium plans. Our RESTful API allows seamless integration with your applications, CMS, or workflow. We provide comprehensive documentation and code examples in multiple languages.'
                ],
                'data_privacy' => [
                    'question' => 'How do you handle my data and privacy?',
                    'answer' => 'We take data privacy seriously. Your content is encrypted during transmission and processing. We don\'t store your content permanently, and it\'s automatically deleted after processing. We never share your data with third parties.'
                ],
                'reports_history' => [
                    'question' => 'Can I access my scan history and reports?',
                    'answer' => 'Yes. All plans include scan history with downloadable reports. You can export results as PDF or CSV files. Professional and Premium plans retain history for 12 months; Essential plan retains for 3 months.'
                ]
            ]
        ],

        'billing' => [
            'title' => 'Billing & Payments',
            'questions' => [
                'payment_methods' => [
                    'question' => 'What payment methods do you accept?',
                    'answer' => 'We accept all major credit cards (Visa, MasterCard, American Express) via Stripe, PayPal, and Alipay. All transactions are secure and encrypted.'
                ],
                'cancel_anytime' => [
                    'question' => 'Can I cancel my subscription anytime?',
                    'answer' => 'Yes, you can cancel your subscription at any time. There are no cancellation fees. Your access will continue until the end of your current billing period.'
                ],
                'refund_policy' => [
                    'question' => 'What is your refund policy?',
                    'answer' => 'We offer a 7-day money-back guarantee for all plans. If you\'re not satisfied with our service within the first 7 days, contact us for a full refund, no questions asked.'
                ],
                'upgrade_downgrade' => [
                    'question' => 'Can I upgrade or downgrade my plan?',
                    'answer' => 'Yes. You can upgrade or downgrade at any time. When upgrading, you\'ll be charged a prorated amount. When downgrading, the change takes effect at your next billing cycle.'
                ],
                'annual_savings' => [
                    'question' => 'How much can I save with annual billing?',
                    'answer' => 'Annual plans save you up to 45% compared to monthly billing. For example, the Professional plan costs $24.99/month annually vs $45.99/month when billed monthly.'
                ],
                'invoice_receipt' => [
                    'question' => 'Will I receive invoices and receipts?',
                    'answer' => 'Yes. You\'ll receive an email receipt immediately after each payment. You can also download invoices anytime from your account dashboard.'
                ]
            ]
        ],

        'support' => [
            'title' => 'Support & Help',
            'questions' => [
                'customer_support' => [
                    'question' => 'How can I contact customer support?',
                    'answer' => 'You can reach our support team via email at support@aigcchecker.com, through the live chat on our website (available 24/7 for Premium users, business hours for others), or by submitting a ticket through your dashboard.'
                ],
                'response_time' => [
                    'question' => 'What is the typical support response time?',
                    'answer' => 'Essential plan: Within 48 hours. Professional plan: Within 24 hours. Premium plan: Priority support with response within 4 hours. Live chat is available for real-time assistance.'
                ],
                'technical_issues' => [
                    'question' => 'What if I encounter technical issues?',
                    'answer' => 'If you experience any technical problems, please contact our support team immediately. We\'ll work to resolve the issue as quickly as possible and extend your subscription if downtime affects your service.'
                ],
                'training_resources' => [
                    'question' => 'Do you provide training or tutorials?',
                    'answer' => 'Yes! We offer comprehensive documentation, video tutorials, and webinars. Professional and Premium users also get access to personalized onboarding sessions and advanced training materials.'
                ],
                'feature_requests' => [
                    'question' => 'Can I request new features?',
                    'answer' => 'Absolutely! We actively listen to our users. Submit feature requests through your dashboard or email us. We regularly review suggestions and prioritize based on user demand.'
                ],
                'enterprise_support' => [
                    'question' => 'Do you offer enterprise support?',
                    'answer' => 'Yes. Enterprise customers get dedicated account managers, custom SLAs, priority support, and tailored solutions. Contact our sales team at enterprise@aigcchecker.com for more information.'
                ]
            ]
        ]
    ],

    'contact' => [
        'title' => 'Still have questions?',
        'description' => 'Can\'t find the answer you\'re looking for? Please chat with our friendly team.',
        'button' => 'Get in touch'
    ]
];
