<?php

return [
    'meta' => [
        'title' => 'About Us - AigcChecker',
        'description' => 'Learn about AigcChecker\'s mission, team, and values. We are committed to providing high-quality AI detection and rewriting services to help users improve content quality and originality.',
        'keywords' => 'About Us, AigcChecker, AI Detection, AI Rewriting, Content Quality, Originality, Team, Values'
    ],
    'about_us' => 'About Us',
    'easy_way' => 'Easy way to reduce your AI content',
    'values' => 'We uphold our core values',
    'ai_detection' => 'AI Content Detection',
    'ai_detection_desc' => 'Help users check if their text is written by AI or human with accurate and fast analysis.',
    'ai_rewrite' => 'AI Text Rewriting',
    'ai_rewrite_desc' => 'Allow users to rewrite and optimize their content with improved clarity and originality.',
    'multilingual' => 'Multilingual Support',
    'multilingual_desc' => 'Provide detection and rewriting in multiple languages for a global audience.',
    'reports' => 'Detailed Reports',
    'reports_desc' => 'Generate clear, professional reports with percentage scores and improvement suggestions.',
    'slogan' => 'Get better results with our AI tools easily',
    'step1' => '1 create your account',
    'step1_desc' => 'Sign up quickly with your email. Access your dashboard to manage your documents and AI tasks.',
    'step2' => '2 upload your text',
    'step2_desc' => 'Upload your document or paste text directly into our platform for instant processing.',
    'step3' => '3 detect or rewrite instantly',
    'step3_desc' => 'Choose to run AI detection or rewrite your content with a single click.',
    'create_an_account' => 'Create an account',
    'step4' => '4 download your results',
    'step4_desc' => 'Download the analyzed or rewritten content in a convenient format.',
    'time_required' => '5 min to complete',
    'customer_feedback' => 'Customer feedback',
    'feedback1' => 'Using the AI detection tool, I was able to quickly identify which parts of my article were likely generated by AI. The detailed percentage report and suggestions helped me make my content more original and readable.',
    'feedback1_author' => 'Michael Howard',
    'feedback1_position' => 'Writer',
    'feedback2' => 'The AI rewriting feature completely transformed my draft. It improved sentence structure, vocabulary, and overall clarity while maintaining my original meaning. It saved me hours of editing.',
    'feedback2_author' => 'Kristin Watson',
    'feedback2_position' => 'Student',
    'from_blog' => 'From the blog',

    // About page content
    'page_title' => 'About Us',
    'page_subtitle' => 'AigcChecker is a leading AI technology company specializing in AI content detection and humanization. We help businesses and individuals ensure content authenticity and optimize AI-generated text for natural, human-like quality.',

    // Stats
    'stats' => [
        'years' => '3+',
        'years_label' => 'Years of Excellence',
        'users' => '50K+',
        'users_label' => 'Global Users',
        'accuracy' => '99%',
        'accuracy_label' => 'Detection Accuracy',
    ],

    // Mission section
    'mission_title' => 'Our Mission: Bridging AI and Human Creativity',
    'mission_content_1' => 'In the rapidly evolving landscape of artificial intelligence, we believe that AI should enhance, not replace, human creativity. Since our founding, we have been dedicated to developing cutting-edge AI detection and humanization technologies that empower users to create authentic, high-quality content.',
    'mission_content_2' => 'Our advanced algorithms can accurately identify AI-generated content while our humanization tools transform robotic text into natural, engaging prose. Whether you\'re a content creator, student, researcher, or business professional, we provide the tools you need to maintain authenticity and originality in an AI-driven world.',

    // Team section
    'team_title' => 'Our Expert Team',
    'team_subtitle' => 'Meet the innovators behind AigcChecker',
    'team_card_text' => 'Passionate about AI ethics and content authenticity, dedicated to pushing the boundaries of what\'s possible.',

    'team_members' => [
        'ceo' => [
            'position' => 'Founder / CEO',
            'name' => 'Sarah Chen',
        ],
        'cto' => [
            'position' => 'Chief Technology Officer',
            'name' => 'David Martinez',
        ],
        'lead_ai' => [
            'position' => 'Lead AI Engineer',
            'name' => 'Emma Thompson',
        ],
        'product' => [
            'position' => 'Product Manager',
            'name' => 'James Wilson',
        ],
    ],

    // Hiring section
    'hiring_text' => 'Want to join our mission?',
    'hiring_link' => 'We are hiring',

    // System messages
    'login_required' => 'Please login first',
    'empty_content' => 'Text content cannot be empty',
    'task_create_failed' => 'Task creation failed, please try again later',
    'task_create_success' => 'Task has been successfully created',
]; 